const express = require("express");
const mainErrorHandler = require("../middleware/mainErrorHandler");
const userLogin = require("../routes/userLogin");
const addTask = require("../routes/addTask");
const updateTask = require("../routes/updateTask");
const deleteTask = require("../routes/deleteTask");
const registerUser = require("../routes/registerUser");
const editProfile = require("../routes/editProfile");
const { getUserInfo } = require("../routes/getUserInfo");
const taskComplete = require("../routes/taskComplete");
const addSubTask = require("../routes/addSubTask");
const updateSubTask = require("../routes/updateSubTask");
const deleteSubTask = require("../routes/deleteSubTask");
const completeSubTask = require("../routes/completeSubTask");
const searchUsers = require("../routes/searchUsers");
const { addComment } = require("../routes/addComments");
const getComments = require("../routes/getComments");
const updateComment = require("../routes/updateComment");
const deleteComment = require("../routes/deleteComment");
const addMember = require("../routes/addTaskMembers");
const exitTaskGroup = require("../routes/exitTaskGroup");
const makeAnAdmin = require("../routes/makeTaskAdmin");
const dismissAnAdmin = require("../routes/dismissAnAdmin");
const removeMember = require("../routes/removeTaskMember");
const { assignMemberForSubtask } = require("../routes/assignMemberForSubtask");
const removeSubtaskMember = require("../routes/removeAssignedMemberOfSubtask");
const reverseTaskCompletion = require("../routes/reverseTaskCompletion");
const reverseSubtaskCompletion = require("../routes/reverseSubtaskCompletion");
const getNotifications = require("../routes/getNotifications");
const rescheduleTask = require("../routes/rescheduleTask");

module.exports = (app) => {
  app.use(express.json({ limit: "50mb" }));
  app.use("/api/login", userLogin);
  app.use("/api/addtasks", addTask);
  app.use("/api/taskupdate", updateTask);
  app.use("/api/taskdelete", deleteTask);
  app.use("/api/register", registerUser);
  app.use("/api/editprofile", editProfile);
  app.use("/api/users", getUserInfo);
  app.use("/api/taskcomplete", taskComplete);
  app.use("/api/addSubTask", addSubTask);
  app.use("/api/updateSubTask", updateSubTask);
  app.use("/api/deleteSubTask", deleteSubTask);
  app.use("/api/completeSubTask", completeSubTask);
  app.use("/api/search-user", searchUsers);
  app.use("/api/add-comment", addComment);
  app.use("/api/get-comments", getComments);
  app.use("/api/update-comment", updateComment);
  app.use("/api/delete-comment", deleteComment);
  app.use("/api/add-member", addMember);
  app.use("/api/exit-task", exitTaskGroup);
  app.use("/api/make-admin", makeAnAdmin);
  app.use("/api/dismiss-admin", dismissAnAdmin);
  app.use("/api/remove-member", removeMember);
  app.use("/api/assign-subtask-member", assignMemberForSubtask);
  app.use("/api/remove-subtask-member", removeSubtaskMember);
  app.use("/api/reverse-task-completion", reverseTaskCompletion);
  app.use("/api/reverse-subtask-completion", reverseSubtaskCompletion);
  app.use("/api/get-notifs", getNotifications);
  app.use("/api/reschedule-task", rescheduleTask);
  app.use(mainErrorHandler);
};
